# Copyright (c) 2026 Long Run Advisory. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: '3.7'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /spec/conditional-lock-v1.yaml
    volumes:
      - ./conditional-lock-v1.yaml:/spec/conditional-lock-v1.yaml
